package net.thevaliantsquidward.rainbowreef.client.animations;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;
import net.minecraftforge.api.distmarker.Dist;
import net.minecraftforge.api.distmarker.OnlyIn;

@OnlyIn(Dist.CLIENT)
public class JellyfishAnimations {

	public static final AnimationDefinition SWIM = AnimationDefinition.Builder.withLength(6.4F).looping()
			.addAnimation("bell", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(-8.66F, 0.0F, -8.66F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.1333F, KeyframeAnimations.degreeVec(-9.66F, 0.65F, -9.24F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.2667F, KeyframeAnimations.degreeVec(-10.0F, 1.29F, -9.66F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.4F, KeyframeAnimations.degreeVec(-9.66F, 1.91F, -9.91F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5333F, KeyframeAnimations.degreeVec(-8.66F, 2.5F, -10.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.6667F, KeyframeAnimations.degreeVec(-7.07F, 3.04F, -9.91F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.8F, KeyframeAnimations.degreeVec(-5.0F, 3.54F, -9.66F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.9333F, KeyframeAnimations.degreeVec(-2.59F, 3.97F, -9.24F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.2F, KeyframeAnimations.degreeVec(2.59F, 4.62F, -7.93F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.3333F, KeyframeAnimations.degreeVec(5.0F, 4.83F, -7.07F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.4667F, KeyframeAnimations.degreeVec(7.07F, 4.96F, -6.09F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.6F, KeyframeAnimations.degreeVec(8.66F, 5.0F, -5.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.7333F, KeyframeAnimations.degreeVec(9.66F, 4.96F, -3.83F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.8667F, KeyframeAnimations.degreeVec(10.0F, 4.83F, -2.59F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.0F, KeyframeAnimations.degreeVec(9.66F, 4.62F, -1.31F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.1333F, KeyframeAnimations.degreeVec(8.66F, 4.33F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.2667F, KeyframeAnimations.degreeVec(7.07F, 3.97F, 1.31F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.4F, KeyframeAnimations.degreeVec(5.0F, 3.54F, 2.59F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.5333F, KeyframeAnimations.degreeVec(2.59F, 3.04F, 3.83F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.8F, KeyframeAnimations.degreeVec(-2.59F, 1.91F, 6.09F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.9333F, KeyframeAnimations.degreeVec(-5.0F, 1.29F, 7.07F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.0667F, KeyframeAnimations.degreeVec(-7.07F, 0.65F, 7.93F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.2F, KeyframeAnimations.degreeVec(-8.66F, 0.0F, 8.66F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.3333F, KeyframeAnimations.degreeVec(-9.66F, -0.65F, 9.24F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.4667F, KeyframeAnimations.degreeVec(-10.0F, -1.29F, 9.66F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.6F, KeyframeAnimations.degreeVec(-9.66F, -1.91F, 9.91F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.7333F, KeyframeAnimations.degreeVec(-8.66F, -2.5F, 10.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.8667F, KeyframeAnimations.degreeVec(-7.07F, -3.04F, 9.91F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.0F, KeyframeAnimations.degreeVec(-5.0F, -3.54F, 9.66F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.1333F, KeyframeAnimations.degreeVec(-2.59F, -3.97F, 9.24F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.4F, KeyframeAnimations.degreeVec(2.59F, -4.62F, 7.93F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.5333F, KeyframeAnimations.degreeVec(5.0F, -4.83F, 7.07F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.6667F, KeyframeAnimations.degreeVec(7.07F, -4.96F, 6.09F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.8F, KeyframeAnimations.degreeVec(8.66F, -5.0F, 5.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.9333F, KeyframeAnimations.degreeVec(9.66F, -4.96F, 3.83F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.0667F, KeyframeAnimations.degreeVec(10.0F, -4.83F, 2.59F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.2F, KeyframeAnimations.degreeVec(9.66F, -4.62F, 1.31F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.3333F, KeyframeAnimations.degreeVec(8.66F, -4.33F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.4667F, KeyframeAnimations.degreeVec(7.07F, -3.97F, -1.31F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.6F, KeyframeAnimations.degreeVec(5.0F, -3.54F, -2.59F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.7333F, KeyframeAnimations.degreeVec(2.59F, -3.04F, -3.83F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(6.0F, KeyframeAnimations.degreeVec(-2.59F, -1.91F, -6.09F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(6.1333F, KeyframeAnimations.degreeVec(-5.0F, -1.29F, -7.07F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(6.2667F, KeyframeAnimations.degreeVec(-7.07F, -0.65F, -7.93F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(6.4F, KeyframeAnimations.degreeVec(-8.66F, 0.0F, -8.66F), AnimationChannel.Interpolations.CATMULLROM)
			))
			.addAnimation("bell", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, 0.88F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.1333F, KeyframeAnimations.posVec(-0.33F, 0.49F, 0.65F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.2667F, KeyframeAnimations.posVec(-0.65F, -0.02F, 1.25F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.4F, KeyframeAnimations.posVec(-0.96F, -0.51F, 1.77F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5333F, KeyframeAnimations.posVec(-1.25F, -0.86F, 2.17F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.6667F, KeyframeAnimations.posVec(-1.52F, -0.98F, 2.41F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.8F, KeyframeAnimations.posVec(-1.77F, -0.86F, 2.5F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.9333F, KeyframeAnimations.posVec(-1.98F, -0.51F, 2.41F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.0667F, KeyframeAnimations.posVec(-2.17F, -0.02F, 2.17F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.2F, KeyframeAnimations.posVec(-2.31F, 0.49F, 1.77F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.3333F, KeyframeAnimations.posVec(-2.41F, 0.88F, 1.25F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.4667F, KeyframeAnimations.posVec(-2.48F, 1.02F, 0.65F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.6F, KeyframeAnimations.posVec(-2.5F, 0.88F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.7333F, KeyframeAnimations.posVec(-2.48F, 0.49F, -0.65F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.8667F, KeyframeAnimations.posVec(-2.41F, -0.02F, -1.25F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.0F, KeyframeAnimations.posVec(-2.31F, -0.51F, -1.77F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.1333F, KeyframeAnimations.posVec(-2.17F, -0.86F, -2.17F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.2667F, KeyframeAnimations.posVec(-1.98F, -0.98F, -2.41F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.4F, KeyframeAnimations.posVec(-1.77F, -0.86F, -2.5F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.5333F, KeyframeAnimations.posVec(-1.52F, -0.51F, -2.41F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.6667F, KeyframeAnimations.posVec(-1.25F, -0.02F, -2.17F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.8F, KeyframeAnimations.posVec(-0.96F, 0.49F, -1.77F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.9333F, KeyframeAnimations.posVec(-0.65F, 0.88F, -1.25F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.0667F, KeyframeAnimations.posVec(-0.33F, 1.02F, -0.65F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.2F, KeyframeAnimations.posVec(0.0F, 0.88F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.3333F, KeyframeAnimations.posVec(0.33F, 0.49F, 0.65F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.4667F, KeyframeAnimations.posVec(0.65F, -0.02F, 1.25F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.6F, KeyframeAnimations.posVec(0.96F, -0.51F, 1.77F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.7333F, KeyframeAnimations.posVec(1.25F, -0.86F, 2.17F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.8667F, KeyframeAnimations.posVec(1.52F, -0.98F, 2.41F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.0F, KeyframeAnimations.posVec(1.77F, -0.86F, 2.5F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.1333F, KeyframeAnimations.posVec(1.98F, -0.51F, 2.41F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.2667F, KeyframeAnimations.posVec(2.17F, -0.02F, 2.17F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.4F, KeyframeAnimations.posVec(2.31F, 0.49F, 1.77F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.5333F, KeyframeAnimations.posVec(2.41F, 0.88F, 1.25F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.6667F, KeyframeAnimations.posVec(2.48F, 1.02F, 0.65F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.8F, KeyframeAnimations.posVec(2.5F, 0.88F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.9333F, KeyframeAnimations.posVec(2.48F, 0.49F, -0.65F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.0667F, KeyframeAnimations.posVec(2.41F, -0.02F, -1.25F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.2F, KeyframeAnimations.posVec(2.31F, -0.51F, -1.77F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.3333F, KeyframeAnimations.posVec(2.17F, -0.86F, -2.17F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.4667F, KeyframeAnimations.posVec(1.98F, -0.98F, -2.41F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.6F, KeyframeAnimations.posVec(1.77F, -0.86F, -2.5F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.7333F, KeyframeAnimations.posVec(1.52F, -0.51F, -2.41F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.8667F, KeyframeAnimations.posVec(1.25F, -0.02F, -2.17F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(6.0F, KeyframeAnimations.posVec(0.96F, 0.49F, -1.77F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(6.1333F, KeyframeAnimations.posVec(0.65F, 0.88F, -1.25F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(6.2667F, KeyframeAnimations.posVec(0.33F, 1.02F, -0.65F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(6.4F, KeyframeAnimations.posVec(0.0F, 0.88F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
			))
			.addAnimation("bell", new AnimationChannel(AnimationChannel.Targets.SCALE,
					new Keyframe(0.0F, KeyframeAnimations.scaleVec(1.12F, 1.05F, 1.12F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.1333F, KeyframeAnimations.scaleVec(1.16F, 1.0134F, 1.16F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.2667F, KeyframeAnimations.scaleVec(1.1766F, 1.0F, 1.1766F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.4F, KeyframeAnimations.scaleVec(1.18F, 1.0134F, 1.18F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.6667F, KeyframeAnimations.scaleVec(1.16F, 1.1F, 1.16F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.8F, KeyframeAnimations.scaleVec(1.12F, 1.15F, 1.12F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.9333F, KeyframeAnimations.scaleVec(1.06F, 1.1866F, 1.06F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.0667F, KeyframeAnimations.scaleVec(1.0034F, 1.2F, 1.0034F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.2F, KeyframeAnimations.scaleVec(0.98F, 1.1866F, 0.98F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.3333F, KeyframeAnimations.scaleVec(1.0034F, 1.15F, 1.0034F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.6F, KeyframeAnimations.scaleVec(1.12F, 1.05F, 1.12F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.8667F, KeyframeAnimations.scaleVec(1.1766F, 1.0F, 1.1766F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.0F, KeyframeAnimations.scaleVec(1.18F, 1.0134F, 1.18F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.2667F, KeyframeAnimations.scaleVec(1.16F, 1.1F, 1.16F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.4F, KeyframeAnimations.scaleVec(1.12F, 1.15F, 1.12F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.5333F, KeyframeAnimations.scaleVec(1.06F, 1.1866F, 1.06F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.6667F, KeyframeAnimations.scaleVec(1.0034F, 1.2F, 1.0034F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.8F, KeyframeAnimations.scaleVec(0.98F, 1.1866F, 0.98F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.9333F, KeyframeAnimations.scaleVec(1.0034F, 1.15F, 1.0034F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.2F, KeyframeAnimations.scaleVec(1.12F, 1.05F, 1.12F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.4667F, KeyframeAnimations.scaleVec(1.1766F, 1.0F, 1.1766F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.6F, KeyframeAnimations.scaleVec(1.18F, 1.0134F, 1.18F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.8667F, KeyframeAnimations.scaleVec(1.16F, 1.1F, 1.16F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.0F, KeyframeAnimations.scaleVec(1.12F, 1.15F, 1.12F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.1333F, KeyframeAnimations.scaleVec(1.06F, 1.1866F, 1.06F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.2667F, KeyframeAnimations.scaleVec(1.0034F, 1.2F, 1.0034F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.4F, KeyframeAnimations.scaleVec(0.98F, 1.1866F, 0.98F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.5333F, KeyframeAnimations.scaleVec(1.0034F, 1.15F, 1.0034F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.8F, KeyframeAnimations.scaleVec(1.12F, 1.05F, 1.12F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.0667F, KeyframeAnimations.scaleVec(1.1766F, 1.0F, 1.1766F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.2F, KeyframeAnimations.scaleVec(1.18F, 1.0134F, 1.18F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.4667F, KeyframeAnimations.scaleVec(1.16F, 1.1F, 1.16F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.6F, KeyframeAnimations.scaleVec(1.12F, 1.15F, 1.12F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.7333F, KeyframeAnimations.scaleVec(1.06F, 1.1866F, 1.06F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.8667F, KeyframeAnimations.scaleVec(1.0034F, 1.2F, 1.0034F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(6.0F, KeyframeAnimations.scaleVec(0.98F, 1.1866F, 0.98F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(6.1333F, KeyframeAnimations.scaleVec(1.0034F, 1.15F, 1.0034F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(6.4F, KeyframeAnimations.scaleVec(1.12F, 1.05F, 1.12F), AnimationChannel.Interpolations.CATMULLROM)
			))
			.addAnimation("tentacles_4", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 14.66F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.1333F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 9.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.2667F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 3.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.4F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5333F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -2.66F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.6667F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -3.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.8F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -2.66F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.9333F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.0667F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 3.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.2F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 9.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.3333F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 14.66F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.4667F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 17.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.6F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 14.66F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.7333F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 9.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.8667F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 3.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.1333F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -2.66F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.2667F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -3.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.4F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -2.66F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.5333F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.6667F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 3.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.8F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 9.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.9333F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 14.66F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.0667F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 17.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.2F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 14.66F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.3333F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 9.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.4667F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 3.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.6F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.7333F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -2.66F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.8667F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -3.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -2.66F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.1333F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.2667F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 3.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.4F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 9.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.5333F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 14.66F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.6667F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 17.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.8F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 14.66F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.9333F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 9.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.0667F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 3.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.2F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.3333F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -2.66F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.4667F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -3.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.6F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -2.66F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.7333F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.8667F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 3.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(6.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 9.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(6.1333F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 14.66F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(6.2667F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 17.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(6.4F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 14.66F), AnimationChannel.Interpolations.CATMULLROM)
			))
			.addAnimation("tentacles_4", new AnimationChannel(AnimationChannel.Targets.SCALE,
					new Keyframe(0.0F, KeyframeAnimations.scaleVec(1.0F, 0.8F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.1333F, KeyframeAnimations.scaleVec(1.0F, 0.75F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.2667F, KeyframeAnimations.scaleVec(1.0F, 0.7134F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5333F, KeyframeAnimations.scaleVec(1.0F, 0.7134F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.0667F, KeyframeAnimations.scaleVec(1.0F, 0.8866F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.3333F, KeyframeAnimations.scaleVec(1.0F, 0.8866F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.8667F, KeyframeAnimations.scaleVec(1.0F, 0.7134F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.1333F, KeyframeAnimations.scaleVec(1.0F, 0.7134F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.6667F, KeyframeAnimations.scaleVec(1.0F, 0.8866F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.9333F, KeyframeAnimations.scaleVec(1.0F, 0.8866F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.4667F, KeyframeAnimations.scaleVec(1.0F, 0.7134F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.7333F, KeyframeAnimations.scaleVec(1.0F, 0.7134F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.2667F, KeyframeAnimations.scaleVec(1.0F, 0.8866F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.5333F, KeyframeAnimations.scaleVec(1.0F, 0.8866F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.0667F, KeyframeAnimations.scaleVec(1.0F, 0.7134F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.3333F, KeyframeAnimations.scaleVec(1.0F, 0.7134F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.8667F, KeyframeAnimations.scaleVec(1.0F, 0.8866F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(6.1333F, KeyframeAnimations.scaleVec(1.0F, 0.8866F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(6.2667F, KeyframeAnimations.scaleVec(1.0F, 0.85F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(6.4F, KeyframeAnimations.scaleVec(1.0F, 0.8F, 1.0F), AnimationChannel.Interpolations.CATMULLROM)
			))
			.addAnimation("tentacles_3", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(14.66F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.1333F, KeyframeAnimations.degreeVec(9.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.2667F, KeyframeAnimations.degreeVec(3.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.4F, KeyframeAnimations.degreeVec(-1.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5333F, KeyframeAnimations.degreeVec(-2.66F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.6667F, KeyframeAnimations.degreeVec(-3.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.8F, KeyframeAnimations.degreeVec(-2.66F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.9333F, KeyframeAnimations.degreeVec(-1.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.0667F, KeyframeAnimations.degreeVec(3.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.2F, KeyframeAnimations.degreeVec(9.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.3333F, KeyframeAnimations.degreeVec(14.66F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.4667F, KeyframeAnimations.degreeVec(17.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.6F, KeyframeAnimations.degreeVec(14.66F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.7333F, KeyframeAnimations.degreeVec(9.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.8667F, KeyframeAnimations.degreeVec(3.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.0F, KeyframeAnimations.degreeVec(-1.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.1333F, KeyframeAnimations.degreeVec(-2.66F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.2667F, KeyframeAnimations.degreeVec(-3.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.4F, KeyframeAnimations.degreeVec(-2.66F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.5333F, KeyframeAnimations.degreeVec(-1.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.6667F, KeyframeAnimations.degreeVec(3.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.8F, KeyframeAnimations.degreeVec(9.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.9333F, KeyframeAnimations.degreeVec(14.66F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.0667F, KeyframeAnimations.degreeVec(17.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.2F, KeyframeAnimations.degreeVec(14.66F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.3333F, KeyframeAnimations.degreeVec(9.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.4667F, KeyframeAnimations.degreeVec(3.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.6F, KeyframeAnimations.degreeVec(-1.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.7333F, KeyframeAnimations.degreeVec(-2.66F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.8667F, KeyframeAnimations.degreeVec(-3.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.0F, KeyframeAnimations.degreeVec(-2.66F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.1333F, KeyframeAnimations.degreeVec(-1.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.2667F, KeyframeAnimations.degreeVec(3.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.4F, KeyframeAnimations.degreeVec(9.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.5333F, KeyframeAnimations.degreeVec(14.66F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.6667F, KeyframeAnimations.degreeVec(17.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.8F, KeyframeAnimations.degreeVec(14.66F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.9333F, KeyframeAnimations.degreeVec(9.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.0667F, KeyframeAnimations.degreeVec(3.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.2F, KeyframeAnimations.degreeVec(-1.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.3333F, KeyframeAnimations.degreeVec(-2.66F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.4667F, KeyframeAnimations.degreeVec(-3.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.6F, KeyframeAnimations.degreeVec(-2.66F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.7333F, KeyframeAnimations.degreeVec(-1.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.8667F, KeyframeAnimations.degreeVec(3.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(6.0F, KeyframeAnimations.degreeVec(9.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(6.1333F, KeyframeAnimations.degreeVec(14.66F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(6.2667F, KeyframeAnimations.degreeVec(17.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(6.4F, KeyframeAnimations.degreeVec(14.66F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
			))
			.addAnimation("tentacles_3", new AnimationChannel(AnimationChannel.Targets.SCALE,
					new Keyframe(0.0F, KeyframeAnimations.scaleVec(1.0F, 0.8F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.1333F, KeyframeAnimations.scaleVec(1.0F, 0.75F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.2667F, KeyframeAnimations.scaleVec(1.0F, 0.7134F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5333F, KeyframeAnimations.scaleVec(1.0F, 0.7134F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.0667F, KeyframeAnimations.scaleVec(1.0F, 0.8866F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.3333F, KeyframeAnimations.scaleVec(1.0F, 0.8866F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.8667F, KeyframeAnimations.scaleVec(1.0F, 0.7134F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.1333F, KeyframeAnimations.scaleVec(1.0F, 0.7134F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.6667F, KeyframeAnimations.scaleVec(1.0F, 0.8866F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.9333F, KeyframeAnimations.scaleVec(1.0F, 0.8866F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.4667F, KeyframeAnimations.scaleVec(1.0F, 0.7134F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.7333F, KeyframeAnimations.scaleVec(1.0F, 0.7134F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.2667F, KeyframeAnimations.scaleVec(1.0F, 0.8866F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.5333F, KeyframeAnimations.scaleVec(1.0F, 0.8866F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.0667F, KeyframeAnimations.scaleVec(1.0F, 0.7134F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.3333F, KeyframeAnimations.scaleVec(1.0F, 0.7134F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.8667F, KeyframeAnimations.scaleVec(1.0F, 0.8866F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(6.1333F, KeyframeAnimations.scaleVec(1.0F, 0.8866F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(6.2667F, KeyframeAnimations.scaleVec(1.0F, 0.85F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(6.4F, KeyframeAnimations.scaleVec(1.0F, 0.8F, 1.0F), AnimationChannel.Interpolations.CATMULLROM)
			))
			.addAnimation("tentacles_2", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -14.66F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.1333F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -9.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.2667F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -3.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.4F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5333F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 2.66F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.6667F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 3.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.8F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 2.66F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.9333F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.0667F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -3.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.2F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -9.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.3333F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -14.66F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.4667F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -17.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.6F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -14.66F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.7333F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -9.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.8667F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -3.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.1333F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 2.66F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.2667F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 3.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.4F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 2.66F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.5333F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.6667F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -3.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.8F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -9.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.9333F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -14.66F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.0667F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -17.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.2F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -14.66F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.3333F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -9.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.4667F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -3.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.6F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.7333F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 2.66F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.8667F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 3.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 2.66F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.1333F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.2667F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -3.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.4F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -9.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.5333F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -14.66F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.6667F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -17.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.8F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -14.66F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.9333F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -9.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.0667F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -3.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.2F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.3333F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 2.66F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.4667F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 3.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.6F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 2.66F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.7333F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.8667F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -3.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(6.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -9.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(6.1333F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -14.66F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(6.2667F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -17.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(6.4F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -14.66F), AnimationChannel.Interpolations.CATMULLROM)
			))
			.addAnimation("tentacles_2", new AnimationChannel(AnimationChannel.Targets.SCALE,
					new Keyframe(0.0F, KeyframeAnimations.scaleVec(1.0F, 0.8F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.1333F, KeyframeAnimations.scaleVec(1.0F, 0.75F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.2667F, KeyframeAnimations.scaleVec(1.0F, 0.7134F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5333F, KeyframeAnimations.scaleVec(1.0F, 0.7134F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.0667F, KeyframeAnimations.scaleVec(1.0F, 0.8866F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.3333F, KeyframeAnimations.scaleVec(1.0F, 0.8866F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.8667F, KeyframeAnimations.scaleVec(1.0F, 0.7134F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.1333F, KeyframeAnimations.scaleVec(1.0F, 0.7134F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.6667F, KeyframeAnimations.scaleVec(1.0F, 0.8866F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.9333F, KeyframeAnimations.scaleVec(1.0F, 0.8866F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.4667F, KeyframeAnimations.scaleVec(1.0F, 0.7134F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.7333F, KeyframeAnimations.scaleVec(1.0F, 0.7134F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.2667F, KeyframeAnimations.scaleVec(1.0F, 0.8866F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.5333F, KeyframeAnimations.scaleVec(1.0F, 0.8866F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.0667F, KeyframeAnimations.scaleVec(1.0F, 0.7134F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.3333F, KeyframeAnimations.scaleVec(1.0F, 0.7134F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.8667F, KeyframeAnimations.scaleVec(1.0F, 0.8866F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(6.1333F, KeyframeAnimations.scaleVec(1.0F, 0.8866F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(6.2667F, KeyframeAnimations.scaleVec(1.0F, 0.85F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(6.4F, KeyframeAnimations.scaleVec(1.0F, 0.8F, 1.0F), AnimationChannel.Interpolations.CATMULLROM)
			))
			.addAnimation("tentacles_1", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(-14.66F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.1333F, KeyframeAnimations.degreeVec(-9.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.2667F, KeyframeAnimations.degreeVec(-3.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.4F, KeyframeAnimations.degreeVec(1.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5333F, KeyframeAnimations.degreeVec(2.66F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.6667F, KeyframeAnimations.degreeVec(3.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.8F, KeyframeAnimations.degreeVec(2.66F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.9333F, KeyframeAnimations.degreeVec(1.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.0667F, KeyframeAnimations.degreeVec(-3.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.2F, KeyframeAnimations.degreeVec(-9.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.3333F, KeyframeAnimations.degreeVec(-14.66F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.4667F, KeyframeAnimations.degreeVec(-17.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.6F, KeyframeAnimations.degreeVec(-14.66F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.7333F, KeyframeAnimations.degreeVec(-9.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.8667F, KeyframeAnimations.degreeVec(-3.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.0F, KeyframeAnimations.degreeVec(1.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.1333F, KeyframeAnimations.degreeVec(2.66F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.2667F, KeyframeAnimations.degreeVec(3.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.4F, KeyframeAnimations.degreeVec(2.66F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.5333F, KeyframeAnimations.degreeVec(1.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.6667F, KeyframeAnimations.degreeVec(-3.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.8F, KeyframeAnimations.degreeVec(-9.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.9333F, KeyframeAnimations.degreeVec(-14.66F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.0667F, KeyframeAnimations.degreeVec(-17.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.2F, KeyframeAnimations.degreeVec(-14.66F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.3333F, KeyframeAnimations.degreeVec(-9.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.4667F, KeyframeAnimations.degreeVec(-3.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.6F, KeyframeAnimations.degreeVec(1.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.7333F, KeyframeAnimations.degreeVec(2.66F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.8667F, KeyframeAnimations.degreeVec(3.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.0F, KeyframeAnimations.degreeVec(2.66F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.1333F, KeyframeAnimations.degreeVec(1.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.2667F, KeyframeAnimations.degreeVec(-3.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.4F, KeyframeAnimations.degreeVec(-9.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.5333F, KeyframeAnimations.degreeVec(-14.66F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.6667F, KeyframeAnimations.degreeVec(-17.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.8F, KeyframeAnimations.degreeVec(-14.66F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.9333F, KeyframeAnimations.degreeVec(-9.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.0667F, KeyframeAnimations.degreeVec(-3.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.2F, KeyframeAnimations.degreeVec(1.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.3333F, KeyframeAnimations.degreeVec(2.66F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.4667F, KeyframeAnimations.degreeVec(3.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.6F, KeyframeAnimations.degreeVec(2.66F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.7333F, KeyframeAnimations.degreeVec(1.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.8667F, KeyframeAnimations.degreeVec(-3.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(6.0F, KeyframeAnimations.degreeVec(-9.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(6.1333F, KeyframeAnimations.degreeVec(-14.66F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(6.2667F, KeyframeAnimations.degreeVec(-17.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(6.4F, KeyframeAnimations.degreeVec(-14.66F, 0.0F, 0.0F), AnimationChannel.Interpolations.CATMULLROM)
			))
			.addAnimation("tentacles_1", new AnimationChannel(AnimationChannel.Targets.SCALE,
					new Keyframe(0.0F, KeyframeAnimations.scaleVec(1.0F, 0.8F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.1333F, KeyframeAnimations.scaleVec(1.0F, 0.75F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.2667F, KeyframeAnimations.scaleVec(1.0F, 0.7134F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5333F, KeyframeAnimations.scaleVec(1.0F, 0.7134F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.0667F, KeyframeAnimations.scaleVec(1.0F, 0.8866F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.3333F, KeyframeAnimations.scaleVec(1.0F, 0.8866F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.8667F, KeyframeAnimations.scaleVec(1.0F, 0.7134F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.1333F, KeyframeAnimations.scaleVec(1.0F, 0.7134F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.6667F, KeyframeAnimations.scaleVec(1.0F, 0.8866F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.9333F, KeyframeAnimations.scaleVec(1.0F, 0.8866F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.4667F, KeyframeAnimations.scaleVec(1.0F, 0.7134F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.7333F, KeyframeAnimations.scaleVec(1.0F, 0.7134F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.2667F, KeyframeAnimations.scaleVec(1.0F, 0.8866F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.5333F, KeyframeAnimations.scaleVec(1.0F, 0.8866F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.0667F, KeyframeAnimations.scaleVec(1.0F, 0.7134F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.3333F, KeyframeAnimations.scaleVec(1.0F, 0.7134F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.8667F, KeyframeAnimations.scaleVec(1.0F, 0.8866F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(6.1333F, KeyframeAnimations.scaleVec(1.0F, 0.8866F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(6.2667F, KeyframeAnimations.scaleVec(1.0F, 0.85F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(6.4F, KeyframeAnimations.scaleVec(1.0F, 0.8F, 1.0F), AnimationChannel.Interpolations.CATMULLROM)
			))
			.addAnimation("thing", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(8.66F, 0.0F, 8.66F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.1333F, KeyframeAnimations.degreeVec(7.07F, 1.25F, 7.93F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.2667F, KeyframeAnimations.degreeVec(5.0F, 2.17F, 7.07F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.4F, KeyframeAnimations.degreeVec(2.59F, 2.5F, 6.09F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5333F, KeyframeAnimations.degreeVec(0.0F, 2.17F, 5.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.6667F, KeyframeAnimations.degreeVec(-2.59F, 1.25F, 3.83F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.8F, KeyframeAnimations.degreeVec(-5.0F, 0.0F, 2.59F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.9333F, KeyframeAnimations.degreeVec(-7.07F, -1.25F, 1.31F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.0667F, KeyframeAnimations.degreeVec(-8.66F, -2.17F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.2F, KeyframeAnimations.degreeVec(-9.66F, -2.5F, -1.31F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.3333F, KeyframeAnimations.degreeVec(-10.0F, -2.17F, -2.59F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.4667F, KeyframeAnimations.degreeVec(-9.66F, -1.25F, -3.83F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.6F, KeyframeAnimations.degreeVec(-8.66F, 0.0F, -5.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.7333F, KeyframeAnimations.degreeVec(-7.07F, 1.25F, -6.09F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.8667F, KeyframeAnimations.degreeVec(-5.0F, 2.17F, -7.07F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.0F, KeyframeAnimations.degreeVec(-2.59F, 2.5F, -7.93F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.1333F, KeyframeAnimations.degreeVec(0.0F, 2.17F, -8.66F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.2667F, KeyframeAnimations.degreeVec(2.59F, 1.25F, -9.24F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.4F, KeyframeAnimations.degreeVec(5.0F, 0.0F, -9.66F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.5333F, KeyframeAnimations.degreeVec(7.07F, -1.25F, -9.91F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.6667F, KeyframeAnimations.degreeVec(8.66F, -2.17F, -10.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.8F, KeyframeAnimations.degreeVec(9.66F, -2.5F, -9.91F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.9333F, KeyframeAnimations.degreeVec(10.0F, -2.17F, -9.66F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.0667F, KeyframeAnimations.degreeVec(9.66F, -1.25F, -9.24F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.2F, KeyframeAnimations.degreeVec(8.66F, 0.0F, -8.66F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.3333F, KeyframeAnimations.degreeVec(7.07F, 1.25F, -7.93F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.4667F, KeyframeAnimations.degreeVec(5.0F, 2.17F, -7.07F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.6F, KeyframeAnimations.degreeVec(2.59F, 2.5F, -6.09F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.7333F, KeyframeAnimations.degreeVec(0.0F, 2.17F, -5.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.8667F, KeyframeAnimations.degreeVec(-2.59F, 1.25F, -3.83F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.0F, KeyframeAnimations.degreeVec(-5.0F, 0.0F, -2.59F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.1333F, KeyframeAnimations.degreeVec(-7.07F, -1.25F, -1.31F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.2667F, KeyframeAnimations.degreeVec(-8.66F, -2.17F, 0.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.4F, KeyframeAnimations.degreeVec(-9.66F, -2.5F, 1.31F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.5333F, KeyframeAnimations.degreeVec(-10.0F, -2.17F, 2.59F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.6667F, KeyframeAnimations.degreeVec(-9.66F, -1.25F, 3.83F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.8F, KeyframeAnimations.degreeVec(-8.66F, 0.0F, 5.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.9333F, KeyframeAnimations.degreeVec(-7.07F, 1.25F, 6.09F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.0667F, KeyframeAnimations.degreeVec(-5.0F, 2.17F, 7.07F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.2F, KeyframeAnimations.degreeVec(-2.59F, 2.5F, 7.93F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.3333F, KeyframeAnimations.degreeVec(0.0F, 2.17F, 8.66F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.4667F, KeyframeAnimations.degreeVec(2.59F, 1.25F, 9.24F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.6F, KeyframeAnimations.degreeVec(5.0F, 0.0F, 9.66F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.7333F, KeyframeAnimations.degreeVec(7.07F, -1.25F, 9.91F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.8667F, KeyframeAnimations.degreeVec(8.66F, -2.17F, 10.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(6.0F, KeyframeAnimations.degreeVec(9.66F, -2.5F, 9.91F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(6.1333F, KeyframeAnimations.degreeVec(10.0F, -2.17F, 9.66F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(6.2667F, KeyframeAnimations.degreeVec(9.66F, -1.25F, 9.24F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(6.4F, KeyframeAnimations.degreeVec(8.66F, 0.0F, 8.66F), AnimationChannel.Interpolations.CATMULLROM)
			))
			.addAnimation("thing", new AnimationChannel(AnimationChannel.Targets.SCALE,
					new Keyframe(0.0F, KeyframeAnimations.scaleVec(1.06F, 1.3732F, 1.06F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.1333F, KeyframeAnimations.scaleVec(1.12F, 1.3F, 1.12F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.2667F, KeyframeAnimations.scaleVec(1.16F, 1.2F, 1.16F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.4F, KeyframeAnimations.scaleVec(1.1766F, 1.1F, 1.1766F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.5333F, KeyframeAnimations.scaleVec(1.18F, 1.0268F, 1.18F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.6667F, KeyframeAnimations.scaleVec(1.1766F, 1.0F, 1.1766F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.8F, KeyframeAnimations.scaleVec(1.16F, 1.0268F, 1.16F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.9333F, KeyframeAnimations.scaleVec(1.12F, 1.1F, 1.12F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.2F, KeyframeAnimations.scaleVec(1.0034F, 1.3F, 1.0034F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.3333F, KeyframeAnimations.scaleVec(0.98F, 1.3732F, 0.98F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.4667F, KeyframeAnimations.scaleVec(1.0034F, 1.4F, 1.0034F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.6F, KeyframeAnimations.scaleVec(1.06F, 1.3732F, 1.06F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.7333F, KeyframeAnimations.scaleVec(1.12F, 1.3F, 1.12F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.8667F, KeyframeAnimations.scaleVec(1.16F, 1.2F, 1.16F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.0F, KeyframeAnimations.scaleVec(1.1766F, 1.1F, 1.1766F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.1333F, KeyframeAnimations.scaleVec(1.18F, 1.0268F, 1.18F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.2667F, KeyframeAnimations.scaleVec(1.1766F, 1.0F, 1.1766F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.4F, KeyframeAnimations.scaleVec(1.16F, 1.0268F, 1.16F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.5333F, KeyframeAnimations.scaleVec(1.12F, 1.1F, 1.12F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.8F, KeyframeAnimations.scaleVec(1.0034F, 1.3F, 1.0034F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.9333F, KeyframeAnimations.scaleVec(0.98F, 1.3732F, 0.98F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.0667F, KeyframeAnimations.scaleVec(1.0034F, 1.4F, 1.0034F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.2F, KeyframeAnimations.scaleVec(1.06F, 1.3732F, 1.06F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.3333F, KeyframeAnimations.scaleVec(1.12F, 1.3F, 1.12F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.4667F, KeyframeAnimations.scaleVec(1.16F, 1.2F, 1.16F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.6F, KeyframeAnimations.scaleVec(1.1766F, 1.1F, 1.1766F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.7333F, KeyframeAnimations.scaleVec(1.18F, 1.0268F, 1.18F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.8667F, KeyframeAnimations.scaleVec(1.1766F, 1.0F, 1.1766F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.0F, KeyframeAnimations.scaleVec(1.16F, 1.0268F, 1.16F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.1333F, KeyframeAnimations.scaleVec(1.12F, 1.1F, 1.12F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.4F, KeyframeAnimations.scaleVec(1.0034F, 1.3F, 1.0034F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.5333F, KeyframeAnimations.scaleVec(0.98F, 1.3732F, 0.98F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.6667F, KeyframeAnimations.scaleVec(1.0034F, 1.4F, 1.0034F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.8F, KeyframeAnimations.scaleVec(1.06F, 1.3732F, 1.06F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.9333F, KeyframeAnimations.scaleVec(1.12F, 1.3F, 1.12F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.0667F, KeyframeAnimations.scaleVec(1.16F, 1.2F, 1.16F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.2F, KeyframeAnimations.scaleVec(1.1766F, 1.1F, 1.1766F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.3333F, KeyframeAnimations.scaleVec(1.18F, 1.0268F, 1.18F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.4667F, KeyframeAnimations.scaleVec(1.1766F, 1.0F, 1.1766F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.6F, KeyframeAnimations.scaleVec(1.16F, 1.0268F, 1.16F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.7333F, KeyframeAnimations.scaleVec(1.12F, 1.1F, 1.12F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(6.0F, KeyframeAnimations.scaleVec(1.0034F, 1.3F, 1.0034F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(6.1333F, KeyframeAnimations.scaleVec(0.98F, 1.3732F, 0.98F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(6.2667F, KeyframeAnimations.scaleVec(1.0034F, 1.4F, 1.0034F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(6.4F, KeyframeAnimations.scaleVec(1.06F, 1.3732F, 1.06F), AnimationChannel.Interpolations.CATMULLROM)
			))
			.addAnimation("center", new AnimationChannel(AnimationChannel.Targets.SCALE,
					new Keyframe(0.0F, KeyframeAnimations.scaleVec(0.99F, 1.025F, 0.99F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.1333F, KeyframeAnimations.scaleVec(0.97F, 1.0433F, 0.97F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.4F, KeyframeAnimations.scaleVec(0.96F, 1.0433F, 0.96F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.6667F, KeyframeAnimations.scaleVec(0.97F, 1.0F, 0.97F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.9333F, KeyframeAnimations.scaleVec(1.02F, 0.9567F, 1.02F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.2F, KeyframeAnimations.scaleVec(1.06F, 0.9567F, 1.06F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.7333F, KeyframeAnimations.scaleVec(0.97F, 1.0433F, 0.97F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.0F, KeyframeAnimations.scaleVec(0.96F, 1.0433F, 0.96F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.2667F, KeyframeAnimations.scaleVec(0.97F, 1.0F, 0.97F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.5333F, KeyframeAnimations.scaleVec(1.02F, 0.9567F, 1.02F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.8F, KeyframeAnimations.scaleVec(1.06F, 0.9567F, 1.06F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.3333F, KeyframeAnimations.scaleVec(0.97F, 1.0433F, 0.97F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.6F, KeyframeAnimations.scaleVec(0.96F, 1.0433F, 0.96F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.8667F, KeyframeAnimations.scaleVec(0.97F, 1.0F, 0.97F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.1333F, KeyframeAnimations.scaleVec(1.02F, 0.9567F, 1.02F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.4F, KeyframeAnimations.scaleVec(1.06F, 0.9567F, 1.06F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.9333F, KeyframeAnimations.scaleVec(0.97F, 1.0433F, 0.97F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.2F, KeyframeAnimations.scaleVec(0.96F, 1.0433F, 0.96F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.4667F, KeyframeAnimations.scaleVec(0.97F, 1.0F, 0.97F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(5.7333F, KeyframeAnimations.scaleVec(1.02F, 0.9567F, 1.02F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(6.0F, KeyframeAnimations.scaleVec(1.06F, 0.9567F, 1.06F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(6.1333F, KeyframeAnimations.scaleVec(1.0483F, 0.975F, 1.0483F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(6.4F, KeyframeAnimations.scaleVec(0.99F, 1.025F, 0.99F), AnimationChannel.Interpolations.CATMULLROM)
			))
			.build();

	public static final AnimationDefinition FLOP = AnimationDefinition.Builder.withLength(4.0F).looping()
			.addAnimation("bell", new AnimationChannel(AnimationChannel.Targets.POSITION,
					new Keyframe(0.0F, KeyframeAnimations.posVec(0.0F, -9.5F, 0.0F), AnimationChannel.Interpolations.LINEAR)
			))
			.addAnimation("bell", new AnimationChannel(AnimationChannel.Targets.SCALE,
					new Keyframe(0.0F, KeyframeAnimations.scaleVec(1.2F, 0.5F, 1.2F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.1667F, KeyframeAnimations.scaleVec(1.2259F, 0.5433F, 1.2259F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.3333F, KeyframeAnimations.scaleVec(1.25F, 0.6299F, 1.25F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.6667F, KeyframeAnimations.scaleVec(1.2866F, 0.3701F, 1.2866F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.8333F, KeyframeAnimations.scaleVec(1.2966F, 0.4567F, 1.2966F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.1667F, KeyframeAnimations.scaleVec(1.2966F, 0.5433F, 1.2966F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.3333F, KeyframeAnimations.scaleVec(1.2866F, 0.6299F, 1.2866F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.6667F, KeyframeAnimations.scaleVec(1.25F, 0.3701F, 1.25F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.8333F, KeyframeAnimations.scaleVec(1.2259F, 0.4567F, 1.2259F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.1667F, KeyframeAnimations.scaleVec(1.1741F, 0.5433F, 1.1741F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.3333F, KeyframeAnimations.scaleVec(1.15F, 0.6299F, 1.15F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.6667F, KeyframeAnimations.scaleVec(1.1134F, 0.3701F, 1.1134F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.8333F, KeyframeAnimations.scaleVec(1.1034F, 0.4567F, 1.1034F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.1667F, KeyframeAnimations.scaleVec(1.1034F, 0.5433F, 1.1034F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.3333F, KeyframeAnimations.scaleVec(1.1134F, 0.6299F, 1.1134F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.6667F, KeyframeAnimations.scaleVec(1.15F, 0.3701F, 1.15F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.8333F, KeyframeAnimations.scaleVec(1.1741F, 0.4567F, 1.1741F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.0F, KeyframeAnimations.scaleVec(1.2F, 0.5F, 1.2F), AnimationChannel.Interpolations.CATMULLROM)
			))
			.addAnimation("tentacles_4", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, -75.0F), AnimationChannel.Interpolations.LINEAR)
			))
			.addAnimation("tentacles_4", new AnimationChannel(AnimationChannel.Targets.SCALE,
					new Keyframe(0.0F, KeyframeAnimations.scaleVec(1.0F, 0.5F, 1.5F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.6667F, KeyframeAnimations.scaleVec(1.0F, 0.4134F, 1.4134F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.3333F, KeyframeAnimations.scaleVec(1.0F, 0.4134F, 1.4134F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.6667F, KeyframeAnimations.scaleVec(1.0F, 0.5866F, 1.5866F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.3333F, KeyframeAnimations.scaleVec(1.0F, 0.5866F, 1.5866F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.8333F, KeyframeAnimations.scaleVec(1.0F, 0.5259F, 1.5259F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.0F, KeyframeAnimations.scaleVec(1.0F, 0.5F, 1.5F), AnimationChannel.Interpolations.CATMULLROM)
			))
			.addAnimation("tentacles_3", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(-75.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
			))
			.addAnimation("tentacles_3", new AnimationChannel(AnimationChannel.Targets.SCALE,
					new Keyframe(0.0F, KeyframeAnimations.scaleVec(1.5F, 0.5F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.6667F, KeyframeAnimations.scaleVec(1.4134F, 0.4134F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.3333F, KeyframeAnimations.scaleVec(1.4134F, 0.4134F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.6667F, KeyframeAnimations.scaleVec(1.5866F, 0.5866F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.3333F, KeyframeAnimations.scaleVec(1.5866F, 0.5866F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.8333F, KeyframeAnimations.scaleVec(1.5259F, 0.5259F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.0F, KeyframeAnimations.scaleVec(1.5F, 0.5F, 1.0F), AnimationChannel.Interpolations.CATMULLROM)
			))
			.addAnimation("tentacles_2", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(0.0F, 0.0F, 75.0F), AnimationChannel.Interpolations.LINEAR)
			))
			.addAnimation("tentacles_2", new AnimationChannel(AnimationChannel.Targets.SCALE,
					new Keyframe(0.0F, KeyframeAnimations.scaleVec(1.0F, 0.5F, 1.5F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.6667F, KeyframeAnimations.scaleVec(1.0F, 0.4134F, 1.4134F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.3333F, KeyframeAnimations.scaleVec(1.0F, 0.4134F, 1.4134F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.6667F, KeyframeAnimations.scaleVec(1.0F, 0.5866F, 1.5866F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.3333F, KeyframeAnimations.scaleVec(1.0F, 0.5866F, 1.5866F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.8333F, KeyframeAnimations.scaleVec(1.0F, 0.5259F, 1.5259F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.0F, KeyframeAnimations.scaleVec(1.0F, 0.5F, 1.5F), AnimationChannel.Interpolations.CATMULLROM)
			))
			.addAnimation("tentacles_1", new AnimationChannel(AnimationChannel.Targets.ROTATION,
					new Keyframe(0.0F, KeyframeAnimations.degreeVec(75.0F, 0.0F, 0.0F), AnimationChannel.Interpolations.LINEAR)
			))
			.addAnimation("tentacles_1", new AnimationChannel(AnimationChannel.Targets.SCALE,
					new Keyframe(0.0F, KeyframeAnimations.scaleVec(1.5F, 0.5F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.6667F, KeyframeAnimations.scaleVec(1.4134F, 0.4134F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.3333F, KeyframeAnimations.scaleVec(1.4134F, 0.4134F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.6667F, KeyframeAnimations.scaleVec(1.5866F, 0.5866F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.3333F, KeyframeAnimations.scaleVec(1.5866F, 0.5866F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.8333F, KeyframeAnimations.scaleVec(1.5259F, 0.5259F, 1.0F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.0F, KeyframeAnimations.scaleVec(1.5F, 0.5F, 1.0F), AnimationChannel.Interpolations.CATMULLROM)
			))
			.addAnimation("thing", new AnimationChannel(AnimationChannel.Targets.SCALE,
					new Keyframe(0.0F, KeyframeAnimations.scaleVec(1.0F, 0.5F, 1.0F), AnimationChannel.Interpolations.LINEAR)
			))
			.addAnimation("center", new AnimationChannel(AnimationChannel.Targets.SCALE,
					new Keyframe(0.0F, KeyframeAnimations.scaleVec(0.9F, 1.0F, 0.9F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(0.6667F, KeyframeAnimations.scaleVec(0.8134F, 1.0F, 0.8134F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(1.3333F, KeyframeAnimations.scaleVec(0.8134F, 1.0F, 0.8134F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(2.6667F, KeyframeAnimations.scaleVec(0.9866F, 1.0F, 0.9866F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.3333F, KeyframeAnimations.scaleVec(0.9866F, 1.0F, 0.9866F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(3.8333F, KeyframeAnimations.scaleVec(0.9259F, 1.0F, 0.9259F), AnimationChannel.Interpolations.CATMULLROM),
					new Keyframe(4.0F, KeyframeAnimations.scaleVec(0.9F, 1.0F, 0.9F), AnimationChannel.Interpolations.CATMULLROM)
			))
			.build();
}