modLoader = "javafml"
loaderVersion = "[32,)"
license = "MIT"

[[mods]]
    modId = "rainbowreef"
    version = "${file.jarVersion}"
    logoFile = "rainbowreef.png"
    authors = "ValiantEnvoy, OmayPaty"
    credits = "Owned and maintained by ValiantEnvoy and OmayPaty, special thanks to Alpha, Gec Master, platypushasnohat, and CodyHuh for help with programming, and to TheIndominator for animating some of the mobs!"
    displayName = "Rainbow Reef"
    description = '''Rainbow Reef is a mod designed to enhance your aquarium experience!'''

[[dependencies.rainbowreef]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,1.20.2)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.rainbowreef]]
    modId = "forge"
    mandatory = true
    versionRange = "[47.1.3,)"
    ordering = "AFTER"
    side = "BOTH"