modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="rainbow_reef.png"
authors="${mod_authors}"
credits="Owned and maintained by ValiantEnvoy and OmayPaty, special thanks to platypushasnohat, and crispytwig for help with programming, and to TheIndominator and Ghoul for animating some of the mobs!"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
